### ISSUE TITLE
Unsupervised loss

### ISSUE THREAD

**Issue by arfeen93** [LeeDoYup/FixMatch-pytorch#15]
why the upsupervised increases first a lot and decreases by very few .At last also, unsupervised loss is greater than what it was initially?

**Comment by LeeDoYup** [comment]
It is because the unsupervised loss is based on the predictions on "strongly" augmented samples.
Strongly augmented samples are hard to predict than other original samples, because of the strong transformation of the original samples.

At first, there is no unsupervised loss because of the confidence masking, because the model does not use the strongly augmented samples, if its pseudo-labels are not confident.
